# Site settings
title: HAI - Sahil Saoji
description: Currently a website where you take an Excel sheet and create data visualizations
baseurl: "/chatbot-app" # the subpath of your site
url: "https://sahilsaoji.github.io" # your site URL

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

# Exclude certain files and directories
exclude:
  - backend/venv
  - backend/node_modules
  - node_modules
